### ISSUE TITLE
Mongojs and dependencies failing

### ISSUE THREAD

**Issue by vatruica** [RobertLarsen/CTFd#2]
When doing an "npm update" i get weird issues related to mongojs and its dependencies. I can narrow down the output by only installing mongojs : 

```
sysuser@deb8-base:~/CTFd$ npm install mongojs
/
> kerberos@0.0.17 install /home/sysuser/CTFd/node_modules/mongojs/node_modules/kerberos
> (node-gyp rebuild) || (exit 0)

/bin/sh: 1: node: not found
gyp: Call to 'node -e "require('nan')"' returned exit status 127. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:344:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/sysuser/CTFd/node_modules/mongojs/node_modules/kerberos
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
mongojs@1.4.1 node_modules/mongojs
├── thunky@0.1.0
├── each-series@1.0.0
├── to-mongodb-core@2.0.0
├── parse-mongo-url@1.1.1
├── xtend@4.0.1
├── once@1.3.2 (wrappy@1.0.1)
├── pump@1.0.1 (end-of-stream@1.1.0)
├── readable-stream@2.0.4 (isarray@0.0.1, process-nextick-args@1.0.3, inherits@2.0.1, util-deprecate@1.0.2, string_decoder@0.10.31, core-util-is@1.0.1)
├── kerberos@0.0.17 (nan@2.0.9)
└── mongodb-core@1.2.22 (bson@0.4.19)
```

Noticeable lines are :
    /bin/sh: 1: node: not found
    gyp: Call to 'node -e "require('nan')"' returned exit status 127. while trying to load binding.gyp

I then google stuff on the node executable not being found and stumbled upon this - http://stackoverflow.com/questions/21168141/can-not-install-packages-using-node-package-manager-in-ubuntu . In short, I symlinked the nodejs executable to node. The noticeable lines above have been replaced by the following : 

```
make: Entering directory '/home/sysuser/CTFd/node_modules/mongojs/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
In file included from ../lib/kerberos.cc:1:0:
../lib/kerberos.h:5:27: fatal error: gssapi/gssapi.h: No such file or directory
 #include <gssapi/gssapi.h>
                           ^
compilation terminated.
kerberos.target.mk:88: recipe for target 'Release/obj.target/kerberos/lib/kerberos.o' failed
make: *** [Release/obj.target/kerberos/lib/kerberos.o] Error 1
make: Leaving directory '/home/sysuser/CTFd/node_modules/mongojs/node_modules/kerberos/build'
```

Now I have no idea on what to do. System is debian8 64bits. Any suggestions ?

**Comment by vatruica** [comment]
Solved by installing

```
  npm install nodejs
  npm install node-gyp
```
